/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linglong_lame_Lame */

#ifndef _Included_com_linglong_lame_Lame
#define _Included_com_linglong_lame_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linglong_lame_Lame
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_linglong_lame_Lame_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_linglong_lame_Lame
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_linglong_lame_Lame_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_linglong_lame_Lame
 * Method:    encode
 * Signature: ([SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linglong_lame_Lame_encode
  (JNIEnv *, jobject, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
